//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 BlastTest.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BLASTTEST_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_PRINTREPORT1                129
#define IDB_BACKIMG                     131
#define IDB_BACKIMG_MC                  132
#define IDB_BITOPENREPORT               135
#define IDB_BTN_QUITWINDOWS             136
#define IDB_BLAST_INDEX_RED             137
#define IDB_PREPAR                      139
#define IDB_REALSE                      140
#define IDB_TestSpBtb                   143
#define IDB_RecordView                  144
#define IDB_UserSetup                   145
#define IDB_TestSpIn                    146
#define IDB_PREPARFINISH                147
#define IDB_RELEASEGRAY                 148
#define IDB_PLATEUP                     149
#define IDB_PLATEDOWN                   150
#define IDB_PLATEUPSTOP                 151
#define IDB_PLATEDOWNSTOP               152
#define IDD_TESTSPDATA                  153
#define IDB_TESTCONDSETUP               155
#define IDD_TESTCONDSETUP               156
#define IDB_TESTSETUPBK                 157
#define IDB_SPSETEUPBK                  158
#define IDD_TESTREPORT                  159
#define IDB_TESTRECORDBK                163
#define IDB_AUTOPLATEBTN                164
#define IDB_MANULPLATEBTN               165
#define IDB_TESTSPINOKBTN               166
#define IDD_USERSETUP                   167
#define IDB_USERSETUPBK                 168
#define IDB_STARTKEYBOARD               169
#define IDB_BLAST_INDEX_GRAY            170
#define IDD_REPORTBILL                  171
#define IDD_DEBUGDLG                    173
#define IDB_BITSELECTED                 175
#define IDD_EDITSPDATA                  176
#define IDB_MANULPRESS                  177
#define IDB_HDYFORWARD                  179
#define IDB_HDYBACK                     180
#define IDB_PRESSSTOP                   181
#define IDB_BACKING                     183
#define IDB_BACKING_MC                  183
#define IDB_BITMAP_MC                   186
#define IDB_AUTOPLATEBTN_ZJ             190
#define IDB_BITMAP2                     191
#define IDB_MANUALPLATEBTN_ZJ           191
#define IDC_GRDISPLAYVIEWER1            1000
#define IDC_BUTTON1                     1001
#define IDC_BTN_REPORT                  1001
#define IDC_Save                        1001
#define IDC_FIND                        1001
#define IDC_STARTKEYBOARD               1001
#define IDC_PRINT                       1001
#define IDC_EDIT1                       1003
#define IDC_EDIT19                      1004
#define IDC_EDIT20                      1005
#define IDC_QUIT_WINDOWS                1006
#define IDC_EDIT21                      1006
#define IDC_EDIT2                       1007
#define IDC_EDIT22                      1007
#define IDC_SONDLEVEL                   1008
#define IDC_EDIT8                       1008
#define IDC_EDIT23                      1008
#define IDC_PLATEHIGHT                  1009
#define IDC_EDIT9                       1009
#define IDC_EDIT24                      1009
#define IDC_BTN_PRAPER                  1010
#define IDC_EDIT25                      1010
#define IDC_BTN_REALSE                  1011
#define IDC_COMBO1                      1012
#define IDC_TESTSEL                     1012
#define IDC_COMBSPNO                    1012
#define IDC_SAVEFILEINTERVAL            1012
#define IDC_BLAST_INDEX                 1013
#define IDC_PERSON                      1013
#define IDC_PLATE_UP                    1014
#define IDC_PLATE_DOWN                  1015
#define IDC_PLATE_UP_STOP               1016
#define IDC_PLATE_DOWN_STOP             1017
#define IDC_EDIT3                       1018
#define IDC_DATAGRID1                   1019
#define IDC_EDIT17                      1019
#define IDC_ADODC1                      1020
#define IDC_EDIT4                       1021
#define IDC_EDIT5                       1022
#define IDC_EDIT6                       1023
#define IDC_DATAGRID2                   1024
#define IDC_DG_OpRecord                 1024
#define IDC_EDIT15                      1024
#define IDC_ADODC2                      1025
#define IDC_EDIT16                      1025
#define IDC_EDIT7                       1026
#define IDC_EDIT10                      1027
#define IDC_EDIT11                      1028
#define IDC_EDIT12                      1029
#define IDC_EDIT13                      1030
#define IDC_EDIT14                      1031
#define IDC_TestSpBtn                   1032
#define IDC_RecordView                  1033
#define IDC_UserSetup                   1034
#define IDC_TestSpInBtn                 1035
#define IDC_TESTCONDSETUP               1036
#define IDC_EPRESSSET                   1037
#define IDC_PRESSSETVALUE               1037
#define IDC_GROUPNO                     1038
#define IDC_ONEGROUPNO                  1039
#define IDC_SPKG                        1040
#define IDC_HUNKG                       1041
#define IDC_TYPE                        1042
#define IDC_HUNHIGHT                    1044
#define IDC_DELSEL                      1045
#define IDC_PRINTREPORT                 1046
#define IDC_OPPLATEBTN                  1047
#define IDC_SLSHRESHOLD                 1048
#define IDC_UserSetupSave               1049
#define IDC_REPORTBILLBTN               1050
#define IDC_CURRENTHIGHT                1050
#define IDC_PRINTVIEW                   1051
#define IDC_REALHIGHT                   1051
#define IDC_TIMEDIS                     1052
#define IDC_SETHIGHT                    1052
#define IDC_BUTTON2                     1053
#define IDC_DEBUGDLG                    1054
#define IDC_CHANGEBLAST                 1055
#define IDC_CODEHIGHT                   1055
#define IDC_BACKUPRECORVE               1056
#define IDC_BACKUP                      1057
#define IDC_EXPORTFILE                  1058
#define IDC_ADJUSTHIGHT                 1058
#define IDC_EDIT18                      1059
#define IDC_ZEROSETBTN                  1059
#define IDC_SYSRESET                    1060
#define IDC_CLEARDATABASE               1061
#define IDC_CORSET                      1062
#define IDC_CORSETBTN                   1063
#define IDC_CORCURRENT                  1064
#define IDC_BTNFILEEXPORT               1065
#define IDC_SMOGREAL                    1066
#define IDC_CORSET2                     1066
#define IDC_PRESSSETOFFSET              1066
#define IDC_SMOGSET                     1067
#define IDC_SMOGSHELD                   1068
#define IDC_TESTTEMP                    1069
#define IDC_TESTHUMI                    1070
#define IDC_SAVEVALUE                   1072
#define IDC_STEPLENGNT                  1073
#define IDC_STEP                        1074
#define IDC_STEPLENGNT2                 1075
#define IDC_PRESSSET                    1075
#define IDC_DEL                         1076
#define IDC_MFCSHELLLIST1               1081
#define IDC_LISTVIEWCTRL1               1082
#define IDC_LIST1                       1083
#define IDC_DELONERECORD                1084
#define IDC_ADDNEW                      1085
#define IDC_HDYFORWARD                  1086
#define IDC_BUTTON4                     1087
#define IDC_HDYBACK                     1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
